### ISSUE TITLE
joystick settings not being loaded back using .uae config 

### ISSUE THREAD

**Issue by a7mag3ddon** [Chips-fr/uae4arm-rpi#29]
When setting joysticks for a game and saving the config, when loading config back the port 0 and port 1 have reset back to nubs as joystick then games don't work with joystick until I manually drop down the port 0/1 box and choose my joystick from the list.

**Comment by AnalogHero** [comment]
Yes this is this a Bug. Im using uae4arm in retropie launching games with .uae Files. Joystick settings are not loaded back.

**Comment by Chips-fr** [comment]
It works well here in raspbian and latest source code. Even if joystick name is changed. Tested only for first joystick. 
Can you give more precision (command line...)?

**Comment by AnalogHero** [comment]
Command line is uae4arm -f game.uae. If you load the same .uae file using the gui it works.

**Comment by Bippym** [comment]
I can confirm this bug. When the saved uae is reloaded the mouse and controller reverts back to nubs. It shows in the config, but does not reload

**Comment by dakota72** [comment]
Also me confirm this bug :(

**Comment by a7mag3ddon** [comment]
I think development has stopped on this emulator.

**Comment by Chips-fr** [comment]
I need more details since it's working here on raspbian.
I choose specific joystick save the configuration exit. Then specific configuration on command line and joystick is already selected.
You can edit configuration to check that it reflect your choice. Ex of specific joystick selected in my configuration file:
joyport1=joy1
joyport1autofire=none
joyport1mode=djoy
joyportfriendlyname1=DragonRise Inc.   Generic   USB  Joystick  
joyportname1=JOY1

whereas with default state I have this :

joyportfriendlyname1=dPad as joystick
joyportname1=JOY0

**Comment by drakonia667** [comment]
Is there's a way to configure arrows+ctrl as fire in previous version?
I'm using Protracker, in latest version sounds lags awfully, so i'm back to earlier version.

**Comment by Chips-fr** [comment]
Not reproduce and no answer for more than one year.
