### ISSUE TITLE
fire on keyboard

### ISSUE THREAD

**Issue by snakeX79** [Chips-fr/uae4arm-rpi#31]
Is possible to redefine fire key on a keyboard ? Default is "Page Down"
How ?

Thanks a lot.

**Comment by pismy** [comment]
Hi, I have the same need with my arcade cabinet using a keyboard encoder controller ([Mini Pac](https://www.ultimarc.com/minipac.html)).

To my understanding there are two mappings :
<pre>
[physical keyboard] <b>--(mapping1)--&gt;</b> [logical buttons (A,B, X, Y, L, R)] <b>--(mapping2)--&gt;</b> [Amiga Event]
</pre>
Am I right ?

Defaults for **mapping1** are:
* HOME key --&gt; A button
* RSHIFT key --&gt; B button
* PAGEDOWN key --&gt; X button
* PAGEUP key --&gt; Y button
* RSHIFT key --&gt; L button
* RCTRL key --&gt; R button

Not sure to have clearly understood custom remappings in uae4arm.

Is it only designed to customize **mapping2** (remapping A, B, X, Y, L, R to alternate Amiga Keys) ?
Is there a way of configuring/overriding **mapping1** ? Or are they hardcoded in uae4arm ?

Otherwise, I'll probably have to clone, tweek and recompile your project...
Thanks.

**Comment by pismy** [comment]
There is a <code>key_for_menu</code> key in the config...
Would be greate to have a <code>key_for_a</code>, <code>key_for_b</code>, <code>key_for_x</code>, <code>key_for_y</code>, ...

**Comment by pismy** [comment]
Done.
I forked the project here: https://github.com/pismy/uae4arm-rpi
Controller mappings are defined as virtual keycodes (VK_*) in config.h

If anyone needs defining other mappings, just clone my repo, edit config.h with your own mappings, and recompile the project.

I'm not a C developper, I don't know it it's the cleanest way to do it, but it worked perfectly for me !

Cheers.

**Comment by dumell** [comment]
Thank you pismy!

I followed your advice about cloning your project and defined the keys for the Picade keyboard encoder where the joystick is configured as the keys up, down, left, right and the six buttons are configured as left ctrl, left alt, space, left shift, z and x. Downloaded and compiled. Works fine.

**Comment by pismy** [comment]
Glad it helped !

**Comment by Chips-fr** [comment]
Modification merged.
