### ISSUE TITLE
I need to know what resolution uae4arm is running at on RPI

### ISSUE THREAD

**Issue by CommodoreOS** [Chips-fr/uae4arm-rpi#67]
I tried look for this answer on the internet but its not there, so the only place I could ask is here, I have ported uae4arm to THEC64 Maxi,(its a Linux replica of the C64 computer) but the resolution is wrong, it shows 2 small double screens across the top part of the screen and they are green so not the right colour, I need to know what resolution it trying to do, uae4arm works but it has a resolution problem, I tried changing the resolution with fbset but no difference, it like it has a set resolution..?
![uae4arm green screens](https://user-images.githubusercontent.com/38408051/135450457-0afbb172-4345-466f-889c-850520c68adf.png)

**Comment by Chips-fr** [comment]
It depends on the target, but for the gui the resolution is handled here:
https://github.com/Chips-fr/uae4arm-rpi/blob/a0e51f676656710dc6079b76e238002e7939cd27/src/od-pandora/gui/main_window.cpp#L182
In early raspbian version the raspberry didn't like to change resolution that's why you can see if defined(RASPBERRY) in order to keep current resolution on raspberry.
Perhaps your platform has same kind of issue. 
So instead of using GUI_WIDTH and GUI_HEIGHT (and possible 16 which is the color depth) for SDL_SetVideoMode try others common value or current screen value...

**Comment by Chips-fr** [comment]
No repo update expect
